name: Lint
on:
  push:
    branches-ignore:
      - "renovate/**"
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup npm
        uses: npm/action-setup@v3
        with:
          version: 9

      - name: Lint Source Files
        run: |
          echo npm version $(npm -v)
          npm ci
          npm run lint
