#name: Lint
#on:
#  push:
#    branches-ignore:
#      - "renovate/**"
#  pull_request:
#
#permissions:
#  contents: read
#
#jobs:
#  lint:
#    name: Lint
#    runs-on: ubuntu-latest
#
#    strategy:
#      fail-fast: false
#      matrix:
#        node-version: [20.x]
#
#    steps:
#      - name: Checkout Source Files
#        uses: actions/checkout@v4
#
#      - name: Setup npm
#        uses: actions/setup-node@v4
#          #          with:
#          #  node-version: 20
#        # - uses: actions/checkout@v4
#
#      - name: Lint Source Files
#        run: |
#          echo npm version $(npm -v)
#          npm ci
#          npm run lint
