name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Lint Source Files
        run: |
          echo npm version $(npm -v)
#         with:
#           node-version: 20.x
#       - name: Install dependencies
#         run: npm ci
#       - name: Install Playwright Browsers
#         run: pnpm exec playwright install --with-deps
#       - name: Run Playwright tests
#         run: pnpm exec playwright test
