name: Run React Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup npm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
